name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      
    - name: Build
      run: go install ./...

    - name: Test
      run: go test -timeout=0 -v -cover ./...
    
    #- name: Vet
    #  run: go vet -v ./...
      
